package sakura.kooi.BridgingSkin.lottery;

import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.bukkit.Material;
import sakura.kooi.BridgingSkin.IllegalMaterial;

/** Curated full 1x1x1 blocks that are safe to use as real bridging blocks. */
public final class FullBlockPrizeCatalog {
    private static final List<String> DEFAULT_NAMES = List.of(
            "STONE", "GRANITE", "POLISHED_GRANITE", "DIORITE", "POLISHED_DIORITE",
            "ANDESITE", "POLISHED_ANDESITE", "COBBLESTONE", "MOSSY_COBBLESTONE",
            "SMOOTH_STONE", "STONE_BRICKS", "MOSSY_STONE_BRICKS",
            "CRACKED_STONE_BRICKS", "CHISELED_STONE_BRICKS",
            "DEEPSLATE", "COBBLED_DEEPSLATE", "POLISHED_DEEPSLATE",
            "DEEPSLATE_BRICKS", "CRACKED_DEEPSLATE_BRICKS", "DEEPSLATE_TILES",
            "CRACKED_DEEPSLATE_TILES", "CHISELED_DEEPSLATE",
            "TUFF", "POLISHED_TUFF", "TUFF_BRICKS", "CHISELED_TUFF",
            "CHISELED_TUFF_BRICKS", "CALCITE", "DRIPSTONE_BLOCK", "CLAY",
            "BRICKS", "PACKED_MUD", "MUD_BRICKS",
            "SANDSTONE", "CHISELED_SANDSTONE", "CUT_SANDSTONE", "SMOOTH_SANDSTONE",
            "RED_SANDSTONE", "CHISELED_RED_SANDSTONE", "CUT_RED_SANDSTONE",
            "SMOOTH_RED_SANDSTONE", "PRISMARINE", "PRISMARINE_BRICKS",
            "DARK_PRISMARINE", "END_STONE", "END_STONE_BRICKS", "PURPUR_BLOCK",
            "PURPUR_PILLAR", "NETHERRACK", "NETHER_BRICKS", "RED_NETHER_BRICKS",
            "CHISELED_NETHER_BRICKS", "CRACKED_NETHER_BRICKS", "BASALT",
            "POLISHED_BASALT", "SMOOTH_BASALT", "BLACKSTONE", "GILDED_BLACKSTONE",
            "POLISHED_BLACKSTONE", "CHISELED_POLISHED_BLACKSTONE",
            "POLISHED_BLACKSTONE_BRICKS", "CRACKED_POLISHED_BLACKSTONE_BRICKS",
            "OBSIDIAN", "CRYING_OBSIDIAN", "QUARTZ_BLOCK", "CHISELED_QUARTZ_BLOCK",
            "QUARTZ_BRICKS", "QUARTZ_PILLAR", "SMOOTH_QUARTZ",

            "OAK_PLANKS", "SPRUCE_PLANKS", "BIRCH_PLANKS", "JUNGLE_PLANKS",
            "ACACIA_PLANKS", "DARK_OAK_PLANKS", "MANGROVE_PLANKS", "CHERRY_PLANKS",
            "PALE_OAK_PLANKS", "BAMBOO_PLANKS", "BAMBOO_MOSAIC",
            "CRIMSON_PLANKS", "WARPED_PLANKS",
            "OAK_LOG", "SPRUCE_LOG", "BIRCH_LOG", "JUNGLE_LOG", "ACACIA_LOG",
            "DARK_OAK_LOG", "MANGROVE_LOG", "CHERRY_LOG", "PALE_OAK_LOG",
            "STRIPPED_OAK_LOG", "STRIPPED_SPRUCE_LOG", "STRIPPED_BIRCH_LOG",
            "STRIPPED_JUNGLE_LOG", "STRIPPED_ACACIA_LOG", "STRIPPED_DARK_OAK_LOG",
            "STRIPPED_MANGROVE_LOG", "STRIPPED_CHERRY_LOG", "STRIPPED_PALE_OAK_LOG",
            "OAK_WOOD", "SPRUCE_WOOD", "BIRCH_WOOD", "JUNGLE_WOOD", "ACACIA_WOOD",
            "DARK_OAK_WOOD", "MANGROVE_WOOD", "CHERRY_WOOD", "PALE_OAK_WOOD",
            "STRIPPED_OAK_WOOD", "STRIPPED_SPRUCE_WOOD", "STRIPPED_BIRCH_WOOD",
            "STRIPPED_JUNGLE_WOOD", "STRIPPED_ACACIA_WOOD", "STRIPPED_DARK_OAK_WOOD",
            "STRIPPED_MANGROVE_WOOD", "STRIPPED_CHERRY_WOOD", "STRIPPED_PALE_OAK_WOOD",
            "BAMBOO_BLOCK", "STRIPPED_BAMBOO_BLOCK", "CRIMSON_STEM", "WARPED_STEM",
            "STRIPPED_CRIMSON_STEM", "STRIPPED_WARPED_STEM", "CRIMSON_HYPHAE",
            "WARPED_HYPHAE", "STRIPPED_CRIMSON_HYPHAE", "STRIPPED_WARPED_HYPHAE",

            "WHITE_WOOL", "ORANGE_WOOL", "MAGENTA_WOOL", "LIGHT_BLUE_WOOL",
            "YELLOW_WOOL", "LIME_WOOL", "PINK_WOOL", "GRAY_WOOL", "LIGHT_GRAY_WOOL",
            "CYAN_WOOL", "PURPLE_WOOL", "BLUE_WOOL", "BROWN_WOOL", "GREEN_WOOL",
            "RED_WOOL", "BLACK_WOOL",
            "WHITE_CONCRETE", "ORANGE_CONCRETE", "MAGENTA_CONCRETE",
            "LIGHT_BLUE_CONCRETE", "YELLOW_CONCRETE", "LIME_CONCRETE", "PINK_CONCRETE",
            "GRAY_CONCRETE", "LIGHT_GRAY_CONCRETE", "CYAN_CONCRETE", "PURPLE_CONCRETE",
            "BLUE_CONCRETE", "BROWN_CONCRETE", "GREEN_CONCRETE", "RED_CONCRETE",
            "BLACK_CONCRETE",
            "TERRACOTTA", "WHITE_TERRACOTTA", "ORANGE_TERRACOTTA",
            "MAGENTA_TERRACOTTA", "LIGHT_BLUE_TERRACOTTA", "YELLOW_TERRACOTTA",
            "LIME_TERRACOTTA", "PINK_TERRACOTTA", "GRAY_TERRACOTTA",
            "LIGHT_GRAY_TERRACOTTA", "CYAN_TERRACOTTA", "PURPLE_TERRACOTTA",
            "BLUE_TERRACOTTA", "BROWN_TERRACOTTA", "GREEN_TERRACOTTA",
            "RED_TERRACOTTA", "BLACK_TERRACOTTA",
            "WHITE_GLAZED_TERRACOTTA", "ORANGE_GLAZED_TERRACOTTA",
            "MAGENTA_GLAZED_TERRACOTTA", "LIGHT_BLUE_GLAZED_TERRACOTTA",
            "YELLOW_GLAZED_TERRACOTTA", "LIME_GLAZED_TERRACOTTA",
            "PINK_GLAZED_TERRACOTTA", "GRAY_GLAZED_TERRACOTTA",
            "LIGHT_GRAY_GLAZED_TERRACOTTA", "CYAN_GLAZED_TERRACOTTA",
            "PURPLE_GLAZED_TERRACOTTA", "BLUE_GLAZED_TERRACOTTA",
            "BROWN_GLAZED_TERRACOTTA", "GREEN_GLAZED_TERRACOTTA",
            "RED_GLAZED_TERRACOTTA", "BLACK_GLAZED_TERRACOTTA",
            "GLASS", "WHITE_STAINED_GLASS", "ORANGE_STAINED_GLASS",
            "MAGENTA_STAINED_GLASS", "LIGHT_BLUE_STAINED_GLASS",
            "YELLOW_STAINED_GLASS", "LIME_STAINED_GLASS", "PINK_STAINED_GLASS",
            "GRAY_STAINED_GLASS", "LIGHT_GRAY_STAINED_GLASS", "CYAN_STAINED_GLASS",
            "PURPLE_STAINED_GLASS", "BLUE_STAINED_GLASS", "BROWN_STAINED_GLASS",
            "GREEN_STAINED_GLASS", "RED_STAINED_GLASS", "BLACK_STAINED_GLASS",

            "COAL_ORE", "DEEPSLATE_COAL_ORE", "IRON_ORE", "DEEPSLATE_IRON_ORE",
            "COPPER_ORE", "DEEPSLATE_COPPER_ORE", "GOLD_ORE", "DEEPSLATE_GOLD_ORE",
            "DIAMOND_ORE", "DEEPSLATE_DIAMOND_ORE", "EMERALD_ORE",
            "DEEPSLATE_EMERALD_ORE", "LAPIS_ORE", "DEEPSLATE_LAPIS_ORE",
            "REDSTONE_ORE", "DEEPSLATE_REDSTONE_ORE", "NETHER_GOLD_ORE",
            "NETHER_QUARTZ_ORE", "COAL_BLOCK", "IRON_BLOCK", "GOLD_BLOCK",
            "DIAMOND_BLOCK", "NETHERITE_BLOCK", "RAW_IRON_BLOCK", "RAW_COPPER_BLOCK",
            "RAW_GOLD_BLOCK", "AMETHYST_BLOCK",
            "COPPER_BLOCK", "EXPOSED_COPPER", "WEATHERED_COPPER", "OXIDIZED_COPPER",
            "WAXED_COPPER_BLOCK", "WAXED_EXPOSED_COPPER", "WAXED_WEATHERED_COPPER",
            "WAXED_OXIDIZED_COPPER", "CUT_COPPER", "EXPOSED_CUT_COPPER",
            "WEATHERED_CUT_COPPER", "OXIDIZED_CUT_COPPER", "WAXED_CUT_COPPER",
            "WAXED_EXPOSED_CUT_COPPER", "WAXED_WEATHERED_CUT_COPPER",
            "WAXED_OXIDIZED_CUT_COPPER", "CHISELED_COPPER", "EXPOSED_CHISELED_COPPER",
            "WEATHERED_CHISELED_COPPER", "OXIDIZED_CHISELED_COPPER",
            "WAXED_CHISELED_COPPER", "WAXED_EXPOSED_CHISELED_COPPER",
            "WAXED_WEATHERED_CHISELED_COPPER", "WAXED_OXIDIZED_CHISELED_COPPER",

            "BONE_BLOCK", "DRIED_KELP_BLOCK", "BROWN_MUSHROOM_BLOCK",
            "RED_MUSHROOM_BLOCK", "MUSHROOM_STEM", "NETHER_WART_BLOCK",
            "WARPED_WART_BLOCK", "SHROOMLIGHT", "SPONGE", "WET_SPONGE",
            "BOOKSHELF", "SNOW_BLOCK", "MOSS_BLOCK", "SCULK", "RESIN_BLOCK",
            "RESIN_BRICKS", "OCHRE_FROGLIGHT", "VERDANT_FROGLIGHT",
            "PEARLESCENT_FROGLIGHT", "GLOWSTONE"
    );

    private static final List<Material> DEFAULTS = loadDefaults();
    private static final Set<Material> ALLOWED = Set.copyOf(DEFAULTS);

    private FullBlockPrizeCatalog() {
    }

    public static List<Material> defaults() {
        return DEFAULTS;
    }

    public static List<String> defaultNames() {
        return DEFAULTS.stream().map(Material::name).toList();
    }

    public static boolean isEligible(Material material) {
        // ALLOWED is deliberately curated rather than inferred from isSolid/isBlock: those
        // broad flags also accept partial/function blocks (stairs, hoppers, etc.).
        return material != null && ALLOWED.contains(material)
                && material != Material.SEA_LANTERN
                && !IllegalMaterial.isIllegal(material);
    }

    private static List<Material> loadDefaults() {
        LinkedHashSet<Material> materials = new LinkedHashSet<>();
        for (String name : DEFAULT_NAMES) {
            Material material = Material.matchMaterial(name);
            if (material == null) {
                throw new IllegalStateException("当前服务端缺少奖池材质 " + name);
            }
            materials.add(material);
        }
        return List.copyOf(materials);
    }
}
