database:
  type: sqlite
  postgresql:
    host: CHANGE_ME
    port: 5432
    database: CHANGE_ME
    user: CHANGE_ME
    password: CHANGE_ME

# 可以进游戏站到目标位置执行 /blocklv setrank 就地设置。
rank:
  x: -188
  y: 45
  z: 1355
  world: world
